name: Create detached commit
description: >-
  Create a detached commit through GitHub API.
  Later, a branch or tag can be created or updated to point to this commit.
  Unlike GraphQL createCommitOnBranch(), this allows updating a pull request
  without triggering unnecessary intermediate events/CI runs.

inputs:
  message:
    description: Commit message
    required: true

  files:
    description: Files to add/update. Supports wildcard patterns.
    required: true

  parent:
    description: Parent commit SHA
    default: ${{ github.sha }}
    required: true

  repository:
    description: Repository name with owner
    default: ${{ github.repository }}
    required: true

  toplevel:
    description: Top-level directory of the repository
    default: .
    required: true

  github-token:
    description: GitHub API token to use
    default: ${{ github.token }}
    required: true

outputs:
  sha:
    description: SHA of the created commit
  url:
    description: API URL of the created commit
  html_url:
    description: Browser URL of the created commit
  tree_sha:
    description: SHA of the created Git tree
  tree_url:
    description: API URL of the created Git tree

runs:
  using: node20
  main: dist/index.js
