name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@v1.0.5
    permissions:
      contents: read
      pull-requests: write
